require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
AllCops:
  TargetRubyVersion: 3.0.5
  Exclude:
    - app/views/**/*
    - bin/*
    - db/**/*
    - vendor/bundle/**/*
  NewCops: enable
Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  CountAsOne: ['array', 'hash']
  IgnoredMethods: ['describe', 'context', 'shared_examples', 'namespace', 'factory']
Metrics/ClassLength:
  CountAsOne: [ 'array', 'hash' ]
Metrics/MethodLength:
  CountAsOne: ['array', 'hash']
Metrics/ModuleLength:
  CountAsOne: [ 'array', 'hash' ]
Rails:
  Enabled: true
Rails/DynamicFindBy:
  Enabled: false
Rails/UnknownEnv:
  Environments:
    - beta
    - development
    - post
    - production
    - staging
    - test
    - uat
RSpec/ExampleLength:
  CountAsOne: ['array', 'hash']
RSpec/MultipleMemoizedHelpers:
  Max: 7
RSpec/NestedGroups:
  Max: 4
Style/Documentation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
